# Generated by Django 4.0.3 on 2022-07-11 20:59

import apps.base.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('grado', models.CharField(help_text='Grado academico alcanzado por el profesional', max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('especialidades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='Especialidades separadas por comas', size=None)),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='HorarioProfesional',
            fields=[
                ('id', models.UUIDField(default=apps.base.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dia', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=7)),
                ('hora_inicio', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], default=12)),
                ('minuto_inicio', models.PositiveSmallIntegerField(choices=[(0, 0), (15, 15), (30, 30), (45, 45)], default=0)),
                ('hora_fin', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], help_text='en blanco para no mostrar', null=True)),
                ('minuto_fin', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (15, 15), (30, 30), (45, 45)], help_text='en blanco para no mostrar', null=True)),
                ('mpp', models.PositiveSmallIntegerField(default=0, help_text='0 para no mostrar', verbose_name='Minutos por paciente')),
                ('especialidades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Especialidades que atiende en este horario', size=None)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='profesionales.profesional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
